apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-serivce
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/deepanshu-rawat6/News-Voyager-frontend-configs.git
    targetRevision: HEAD
    path: dev/frontend
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
