# Frontend Rollout
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: frontend-rollout
  namespace: news-voyager
spec:
  replicas: 3
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: {}
        - setWeight: 40
        - pause: { duration: 20 }
        - setWeight: 60
        - pause: { duration: 20 }
        - setWeight: 80
        - pause: { duration: 20 }
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: frontend-rollout
  template:
    metadata:
      labels:
        app: frontend-rollout
    spec:
      containers:
        - name: frontend
          image: deepanshurawat6/frontend:1.0.0
          resources:
            requests:
              cpu: 200m
              memory: 0.3Gi
            limits:
              cpu: 400m
              memory: 0.6Gi
          ports:
            - containerPort: 5173
          env:
            - name: BACKEND_URL
              value: "http://backend-rollout-service:3001"